src/bft.rs
src/consensus.rs
src/creator.rs
src/extender.rs
src/lib.rs
src/member.rs
src/signed.rs
src/testing.rs
src/units.rs

Please wait for the PR to aleph-node

Refactor Signatures and Keyboxes

---

src/signed.rs
src/signed/tests.rs

A signed object is now required to implement the `Index` trait (not to confuse with the `std::ops::Index` trait)

Require a signed object to implement `Index`

---

.gitignore
cov_report.sh
gen_cov_data.sh
src/member.rs
src/signed.rs
src/signed/tests.rs
src/testing/byzantine.rs
src/testing/mock.rs

- scripts for code coverage generation
- more tests in signed
- some fixes in signed

cov scripts and small changes in signed

---

src/rmc.rs
src/rmc/tests.rs
src/signed.rs
src/signed/tests.rs

Writing tests for RMC exposed a serious bug which prevented tasks from being scheduled. The bug is fixed, and the RMC was slightly refactored

RMC Box Tests

---

Cargo.toml
README.md
examples/dummy_honest.rs
src/alerts.rs
src/member.rs
src/network.rs
src/rmc.rs
src/signed.rs
src/testing/byzantine.rs
src/testing/mock.rs

Commit music: https://dubiozakolektiv.bandcamp.com/track/alarm-song

Implement actual alerts using RMC

---

src/signed.rs

Remove Eq requirement for a Signature
Make internals of Multisigned public

Small changes before bumping the AlephBFT version in aleeph-node

---

examples/blockchain/network.rs
examples/dummy_honest.rs
src/member.rs
src/runway.rs

An update of libp2p broke our example. This PR fixes that.

A0-367: Fix AlephBFT example

---

.github/workflows/post-dod-checklist.yml

I checked and it works, including checkboxes. :3

A0-409: Add DoD reminder

---

.github/workflows/version-bump.yml

Tested here
https://github.com/maciejnems/AlephBFT/actions/runs/1444546007

Disable version bump workflow on forks

---

src/member.rs
src/runway.rs

This reverts commit e1ff059ef17a29bdd83ec5800bfccc4ccee09822.

Revert "debug"

---

Cargo.lock
Cargo.toml
fuzz/Cargo.lock
src/consensus.rs
src/creation/mod.rs
src/member.rs
src/runway.rs

AZ-447: Make member die when killed, even early

---

.github/workflows/gh-pages.yml
.github/workflows/publish-packages.yml

[A0-532](https://cardinal-cryptography.atlassian.net/browse/A0-532)

AZ-707 Push packages to crates.io as a part of CI 

---

Cargo.lock
examples/blockchain/Cargo.toml
examples/blockchain/src/main.rs
examples/ordering/Cargo.toml
examples/ordering/src/main.rs

This is needed to unblock #215. The only difference is that the time in example logs are in UTC.

Substitute `chrono` crate with `time`

---

Cargo.lock
README.md
consensus/Cargo.toml
consensus/src/alerts/mod.rs
consensus/src/member.rs
consensus/src/runway/collection.rs
consensus/src/runway/mod.rs
consensus/src/runway/packer.rs
consensus/src/testing/byzantine.rs
consensus/src/units/mod.rs
consensus/src/units/store.rs
consensus/src/units/validator.rs
crypto/Cargo.toml
crypto/src/signature.rs
mock/Cargo.toml
rmc/Cargo.toml
rmc/src/lib.rs
types/Cargo.toml
types/src/dataio.rs

I tried to spawn everything under member with the exception of the initial unit collection - this one seems like it only happens once, so it doesn't really matter?

A0-1200: Spawn member components

---

consensus/Cargo.toml
consensus/src/backup/saver.rs

unit test for backup saver which asserts that we get responses from backup in the same order they arrived in backup.

A0-3138: Saver unit test

---

Cargo.lock
README.md
consensus/Cargo.toml
consensus/src/alerts/service.rs
consensus/src/backup/loader.rs
consensus/src/backup/mod.rs
consensus/src/backup/saver.rs
consensus/src/runway/mod.rs
consensus/src/testing/alerts.rs
consensus/src/testing/crash_recovery.rs

Remove alert backup since the task got abandoned for now.

A0-1505: Remove alert backup

---

Cargo.lock
consensus/Cargo.toml

A0-3868: Dependabot

---

.github/dependabot.yml

A similar approach to grouping Dependabot PRs that we've recently introduced in `aleph-node`.

A0-3838: Group dependabot PRs

---

.github/workflows/cargo-audit.yml
.github/workflows/check-version-bumped-consensus.yml
.github/workflows/check-version-bumped-crypto.yml
.github/workflows/check-version-bumped-mock.yml
.github/workflows/check-version-bumped-rmc.yml
.github/workflows/check-version-bumped-types.yml
.github/workflows/ci.yml
.github/workflows/readme-cargo-toml-versions-aligned-consensus.yml

We need to add the `merge_group:` trigger in all workflows that have the `pull_request:` trigger.

Add triggers for merge queue

---

Cargo.lock
consensus/Cargo.toml
consensus/src/dissemination/mod.rs
consensus/src/dissemination/task.rs

Additional logs to better figure out what's going on with them gaps.

A0-0000: Logging in dissemination
