Cargo.toml
src/consensus.rs
src/creator.rs
src/lib.rs
src/member.rs
src/terminal.rs
src/testing.rs
src/units.rs
src/units/store.rs

Refactor of the module `units`. The following changes are introduced:
* the implementation of `UnitStore` is moved to a new separate file `src/units/store.rs`,
* the structs in the module are reordered in a more natural order.
* the coordinates of the unit (`UnitCoord`) now store the round number as `u16` instead of `u64`.
* every struct which had fields `round: Round` and `creator: NodeIndex` has them now replaced with `coord: UnitCoord`
* the type of the set of parents in `ControlHash` is changed from `Vec<bool>` with `bit_vec::BitVec<u32>` which consists of roughly N bits.
* in order to standardize the interface, all fields of the `*Unit` structs are made private and are accesed via getters. For convenience, we also have getters to access fields of fields, so that instead of …

Refactor units

---

src/lib.rs
src/terminal.rs
src/units.rs

Adding the `Default` trait for the associated type `Hash` in the `Hasher` trait was unnecessary (and breaks aleph-node). This PR undoes adding this trait

Undo adding Default trait for Hasher::Hash

---

src/lib.rs
src/member.rs
src/nodes.rs
src/signed.rs
src/signed/tests.rs
src/units.rs

`BoolNodeMap` is a struct with the same functionality as `NodeMap<bool>` but with efficient encoding.
`MultiKeychain` is a new trait extending `KeyBox` with multisigning functionality. Also, as an equivalent of `Signed<'a, T, KB>` for multisignatures, two struct are introduced: `PartiallyMultisigned<'a, T, MK>` and
`MultiSigned<'a, T, MK>`.

Implement BoolNodeMap and multisigning tools

---

src/testing/byzantine.rs
src/testing/crash.rs
src/testing/mock.rs
src/testing/mod.rs

Tests for Member, including tests with a "byzantine Member".
What these tests do is essentially checking if Member works correctly, i.e., that if a set of Members connected via network (mock in this case) achieves their intended goal, i.e., consistently order some pieces of "Data".
There are test scenarios with honest Members only, and ones where there are byzantine Members, who make unit forks.
Currently the slowest test runs quite long (i.e., depending on randomness between 20s - 30s):
1) This is because there are hardcoded delays of the order of "a couple of secs", for replaying requests for parents (when there is wrong control hash detected etc.). One TODO would be to add these delays to Member configuration.
2) Another reason is that requests at the moment are rather inefficient, in …

Byzantine tests

---

src/config.rs
src/consensus.rs
src/creator.rs
src/lib.rs
src/member.rs
src/testing/mock.rs
src/units/store.rs

Moves global constants to the configuration of Member.
Adds better control on the delays of the protocol: now by default the create delays till round 3000 (out of default 5000 rounds) are 500ms, and from round 3000 on start to exponentially increase (by a factor of 1.005), so that round 5000 is virtually impossible to reach. This mechanism helps as follows:
1) The honest nodes will now never reach the round limit: 5000
2) The protocol becomes more resistant against crashes/network failures, issues with the DataIO (block production, in practice).

Enhanced configuration of delays. !! Don't merge before the Network change in aleph-node !!

---

src/lib.rs
src/nodes.rs
src/rmc.rs
src/signed.rs
src/signed/tests.rs
src/testing/unreliable.rs

A simple implementation of RMC Box.
The struct `ReliableMulticast<'a, H: Signable + Hash, MK: MultiKeychain>` multicasts hashes of the type `H` and provides the public methods:
* `pub fn new(...) -> Self`,
* `pub fn start_rmc(&mut self, hash: H) -> Result<(), HashAlreadyExistsError>`,
* `pub async fn next_multisigned_hash(&mut self) -> Option<Multisigned<'a, H, MK>>`.
In order for the box to progress, the function `next_multisigned_hash` needs to be polled.

Reliable Multicast Implementation

---

Cargo.toml
examples/dummy_honest.rs
src/alerts.rs
src/lib.rs
src/member.rs
src/rmc.rs
src/signed.rs
src/testing/byzantine.rs
src/testing/mock.rs
src/testing/rmc.rs
src/testing/signed.rs
src/units.rs

Modify the `KeyBox` trait so that the `sign` method is `async`. This is because blocking signing in deprecated in substrate.

Add support for asynchronous signing in KeyBox

---

Cargo.toml
examples/dummy_honest.rs
src/lib.rs
src/signed.rs
src/testing/mock.rs
src/testing/rmc.rs
src/testing/signed.rs

This PR adds a `DefaultMultiKeychain<KB: KeyBox>` struct, which is a simple implementation of `MultiKeyChain` where a multisignature is simply a list of signatures.

Add simple multisignatures to AlephBFT

---

src/rmc.rs
src/signed.rs
src/testing/alerts.rs
src/testing/rmc.rs
src/testing/signed.rs

Mostly make the `Indexed` wrapper more transparent, but also some
improvements to documentation and a more uniform interface.

Clean up `signed` interface

---

examples/blockchain/main.rs
examples/blockchain/network.rs
examples/blockchain/run_blockchain.sh

The fix is a combination of two changes:
-- compiling with `--release` is necessary for speed
-- `yamux` multiplexer was replaced by `mplex` to deal with large bandwidth >> 0.5MB/s

Fixed low tps.

---

src/creator.rs
src/extender.rs
src/member.rs
src/rmc.rs
src/terminal.rs

We decided to panic when the receiving end of channel is closed. It is done by calling `.expect(...)` on send result.

Fix of TOB-ALEPH-009 (Inconsistent closed channel error handling) 

---

src/alerts.rs
src/config.rs
src/creator.rs
src/extender.rs
src/lib.rs
src/nodes.rs
src/testing/byzantine.rs
src/testing/crash.rs
src/testing/dag.rs
src/testing/mock.rs
src/testing/unreliable.rs
src/units.rs
src/units/store.rs

Also makes usage of `NodeIndex` and `NodeCount` more consistent, since it was a natural opportunity to do this.

TOB-ALEPH-002 (consistent usage of Round)

---

src/consensus.rs
src/member.rs

TaskHandles were not awaited by main components causing panics on exit in member and consensus.

FIX: TaskHandle

---

Cargo.toml
README.md
docs/src/aleph_bft_api.md
examples/blockchain/network.rs
examples/dummy_honest.rs
fuzz/src/fuzz.rs
mock/src/lib.rs
src/lib.rs
src/network.rs
src/testing/byzantine.rs
src/testing/mock.rs

Remove the errors and coalesce the two methods into one, exposing the
Recipient enum as a better interface.

Change the Network trait

---

Cargo.toml
src/creator.rs
src/member.rs
src/terminal.rs
src/testing/consensus.rs
src/testing/mock.rs

The issue was that in a certain very unlucky situations involving forks it could happen that an honest unit creator would not be able to answer a parents request for its own unit (it wouldn't be able to decode the control hash). 
Very roughly speaking the reason for that was that in the terminal we only remember one unit variant (=fork) in the `unit_by_coord` map (Terminal), and more specifically (prior to this fix) this was always the most recent variant we received. This map is used when trying to decode parents -- if the parents units from this map do not agree with the control hash, a `WrongControlHash` notification is sent. It could happen, that a unit U was created, referring to a parent V1, and then before this unit U was added to the DAG, another variant V2 could be added to DAG …

Fixed bug with wrong control hash of self unit.

---

src/member.rs

Two improvements of requests in member.
* when multiple units trigger a "missing unit" notification for their common parent, multiple tasks requesting the unit with an appropriate coordinates were created. Now we have at most one task for every (creator, round) coordinate.
* when we need parents of the unit with a given hash, we used to periodically send requests to random peers. This PR optimizes it by always sending the first request for a given hash to the peer who created the corresponding unit (who is most likely to own ).
EDIT: currently we also use the latter improvement in the case when we need a unit with given coordinates

A0-231: Two improvements of requests in member

---

src/creator.rs

- FIX: parents_rx in creator.rs was called multiple times after it returned None (calling next() after stream is empty) blocking creator from gracefully exiting.
- removed "as usize" calls from creator

FIX: towards graceful exit - creator.rs was calling a possibly "finished" stream

---

src/alerts.rs
src/consensus.rs
src/creator.rs
src/extender.rs
src/member.rs
src/network.rs
src/runway.rs
src/terminal.rs

removed calls to `expect` from our services, instead attempting to gracefully exit

graceful exit

---

Cargo.toml
src/consensus.rs
src/creator.rs
src/member.rs
src/runway.rs
src/signed.rs
src/testing/consensus.rs
src/testing/dag.rs
src/testing/mock.rs
src/units/store.rs

The version of https://github.com/Cardinal-Cryptography/AlephBFT/pull/134 built on top of `member.rs` refactor (https://github.com/Cardinal-Cryptography/AlephBFT/pull/135)

A0-249 + A0-250: Node crash recovery

---

src/runway.rs

This PR introduces two changes:
First, it introduces broadcasting each unit created by us immediately after it is added to dag, and secondly, it resolves a missing coordinate request at the moment of adding it to a store instead of doing it at the moment when it is added to dag

A0-427: Broadcast own unit after adding to dag

---

.github/workflows/push-foundation-repo.yml

Now the workflow has access to pushing to foundation repository and triggers only on push to Cardinal-Cryptography repo

AZ-62: Fix synchronization workflow with foundation repository

---

Cargo.lock
consensus/Cargo.toml
consensus/src/creation/creator.rs
consensus/src/runway/backup.rs
consensus/src/runway/mod.rs
consensus/src/units/mod.rs
consensus/src/units/testing.rs
consensus/src/units/validator.rs

This is a first part of adding backup loading mechanism. It introduces an implementation of backup loading mechanism that is yet to be integrated.
The idea is that backup mechanism reads Unit data from a file. After that it waits for response from unit collection. Upon receiving unit collection result it check highest round that was backed up. If unit collection had lower result, the backup mechanism sends all units to add them to dag and after that sends the starting round to creator.

A0-543: Add backup loading mechanism

---

mock/Cargo.toml

Missed that in the previous PR

aleph-bft-mock also needs version bump

---

consensus/Cargo.toml
consensus/src/alerts/mod.rs

[PR 186](https://github.com/Cardinal-Cryptography/AlephBFT/pull/186) promised that tests would be added later. These are those tests.

A0-539: Add more tests for the alerter (fka AZ-340)

---

Cargo.lock
consensus/Cargo.toml
rmc/Cargo.toml

Some API changes got missed during previous work and 0.3.1 was
incompatible with 0.3.0, which ain't acceptable. We also have to yank
0.3.1.

Bump RMC version

---

Cargo.lock
consensus/Cargo.toml
consensus/src/member.rs

**Problem:** In some situations we can observe massive log lines from AlephBFT.
**Reproduction:** 
```bash
./scripts/run_nodes.sh
./scripts/run_nodes.sh -v 2
```
You will see lines like:
```
2022-07-22 16:35:04.119  INFO tokio-runtime-worker AlephBFT-member: Member status report: task queue content: CoordRequest - 46, ParentsRequest - 0, UnitMulticast - 1, RequestNewest - 1; not_resolved_coords.len() - 46; pending tasks with counter >= 5 - ScheduledTask(CoordRequest(UnitCoord { round: 0, creator: NodeIndex(3) }), counter 17), ScheduledTask(CoordRequest(UnitCoord { round: 2, creator: NodeIndex(3) }), counter 17), ScheduledTask(CoordRequest(UnitCoord { round: 1, creator: NodeIndex(3) }), counter 17), ScheduledTask(CoordRequest(UnitCoord { round: 4, creator: NodeIndex(3) }), counter 17), …
```

A0-1163: Do not log large collection of pending tasks

---

.github/workflows/ci.yml
Cargo.toml

The crash recovery tests are flaky. It seems they sometimes overload the
machine with the 20 or so simulated workers producing messages faster
than they can process them. With opt-level=3 it doesn't seem to happen.
Compilation from a clean state is somewhat longer (46 seconds vs 18
seconds in the one test I did), but you don't often recompile all the
dependencies so this shouldn't be such an issue.
I also reenabled "medium" tests on CI - I hope they will pass now and
it's misleading to have them in the repo but not run on CI anyway.

Set opt-level to 3 in test

---

examples/ordering/run.sh
examples/ordering/src/network.rs

This solves the problem of establishing a connection with every network
send which seemed to blow up the system's capability to make more
connections in some circumstances. At the same time, the mock network
remains simple with no tracking of open connections and reconnection
attempts. A potential downside is that the UDP datagrams may be lost,
however this should rarely happen locally and the protocol should be
resistant to that in any case.
Some results:
* `./run.sh -n 15 -m 20 -c 6 -o 30 -d 15` - now passes while it hangs at some point on `main`
* `./run.sh -n 30 -m 5 -c 6 -o 30 -d 15` - still doesn't work (because of lack of censorship resistance, it seems)

A0-1045: Rewrite network in ordering example to UDP

---

Cargo.lock
consensus/Cargo.toml
consensus/src/consensus.rs
consensus/src/lib.rs
consensus/src/member.rs
consensus/src/runway/mod.rs
consensus/src/terminator.rs

Earlier we introduced selects which wait for unspawned tasks, in order to enable synchronized termination. Now, since all our components are spawned, this is no longer needed.

A0-1253 Remove unnecessary wait selects from member and runway

---

Cargo.lock
consensus/Cargo.toml
consensus/src/creation/creator.rs
consensus/src/creation/mod.rs

1. slightly refactored creator.rs: added `UnitsCollector`; added more detailed `trace` logging
2. setting initial delay to `30` minutes in creator if `can_create` flag is true - it should help in situations when we are still waiting for our own unit

creator.rs

---

Cargo.lock
consensus/Cargo.toml
consensus/src/testing/mod.rs
examples/blockchain/src/main.rs
fuzz/src/lib.rs
mock/Cargo.toml
mock/src/dataio.rs

* Removed unnecessary cloning a `vec` under a `mutex`
* Refactored the `Saver::new` function to take no arguments.
* Implemented `From` trait for `Saver` which creates a Saver from existing data (same behavior as ::new before the refactor)

A0-1054: Simplify mock Saver and Loader.

---

Cargo.lock
consensus/Cargo.toml
consensus/src/runway/backup.rs

Extracted from the function `prepare_test` all the logic related to:
* selecting which units should appear in the backup source,
* simulating ABFT to create units,
* composing unit encodings to form the backup source 
* corrupting the backup source.
So that the function `prepare_test` receives the already prepared backup source as an argument, and its only responsibility is to prepare the loading mechanism, and return appropriate handles and channel endpoints. As a result:
* testing backup is more flexible - with extracted logic it is possible test new different scenarios,
* test cases are more readable - they prepare backup sources explicitly by themselves.

A0-2504: More intuitive and flexible tests for unit backup.

---

Cargo.lock
README.md
consensus/Cargo.toml
consensus/src/config.rs
consensus/src/consensus.rs
consensus/src/creation/mod.rs
consensus/src/lib.rs
consensus/src/member.rs
consensus/src/runway/mod.rs
consensus/src/testing/consensus.rs
consensus/src/testing/creation.rs
consensus/src/testing/dag.rs
consensus/src/testing/mod.rs
examples/blockchain/src/main.rs
examples/ordering/src/main.rs
fuzz/src/lib.rs

Add a function which can be used to check whether reaching the maximum round takes large enough amount of time. The function is not called in AlephBFT as various projects which use aleph-bft may expect different delays. Instead the function is publically exposed to be called in the project which uses AlephBFT.
Tests:
* checked that `ordering` and `blockchain` examples work well
* checked that `aleph-node` (after needed changes) works with this version of AlephBFT (but turned out we also need to make `default_delay_config` public)

A0-2583: Prevent reaching max round too fast

---

Cargo.lock
README.md
consensus/Cargo.toml
consensus/src/alerts/mod.rs
consensus/src/network.rs
consensus/src/runway/backup.rs
consensus/src/runway/collection.rs
consensus/src/runway/mod.rs
consensus/src/runway/packer.rs
consensus/src/testing/alerts.rs
consensus/src/testing/byzantine.rs
consensus/src/testing/unreliable.rs
consensus/src/units/store.rs
consensus/src/units/testing.rs
consensus/src/units/validator.rs
crypto/Cargo.toml
crypto/src/signature.rs
docs/src/aleph_bft_api.md
fuzz/src/lib.rs
mock/Cargo.toml
mock/src/crypto/keychain.rs
mock/src/crypto/wrappers.rs
mock/src/network.rs
rmc/Cargo.toml
rmc/src/lib.rs
types/Cargo.toml

The general change was to make `sign(...)` in `crypto/signature::Keychain` synchronous. 
Removal of 1 `async` keyword caused all the other changes... The other changes included:
* removal of `async` from other functions
* removal of `await` in function calls which were no longer `async`
* changing `#[tokio::test]` to `#[test]` if a test was no longer `async`
* removal of one `#[async_trait]`
* possibly some other minor stuff.

A0-2883: Make keychain synchronous

---

Cargo.lock
consensus/Cargo.toml
crypto/Cargo.toml
crypto/src/node.rs
rust-toolchain.toml

Dependabot stopped opening PRs [[log]](https://github.com/Cardinal-Cryptography/AlephBFT/network/updates/676473017) due to too low rust version. This PR bumps rust to 1.68.2 stable (same as aleph-node) and updates most dependencies (`cargo update`).

A0-3039: fix dependabot & bump rust version

---

Cargo.lock
README.md
consensus/Cargo.toml
consensus/src/backup/loader.rs
consensus/src/backup/mod.rs
consensus/src/backup/saver.rs
consensus/src/lib.rs
consensus/src/runway/mod.rs
consensus/src/testing/crash_recovery.rs

Former `runway/backup.rs` contained two services - `BackupSaver` and `BackupLoader`.
Created a module `backup` and moved `BackupSaver` and `BackupLoader` to its separate submodules.
Tests in former `backup.rs` only considered `BackupLoader` so moved them to `backup/loader.rs`.

A0-3137: Split backup into submodules

---

Cargo.lock
consensus/Cargo.toml
rmc/Cargo.toml
rmc/src/lib.rs

Refactor `DoublingDelayScheduler` - channel communication between `add_task` and `next_task` was not needed.
`add_task` and `next_task` take `&mut self` so it's impossible to add a task while awaiting some other task's delay in `next_task`. This way it is guaranteed that when a task is added by `add_task`, the next call to `next_task` considers this task before other tasks with long delays.
Added a small unit test

A0-3186: Simplify DoublingDelayScheduler

---

Cargo.lock
README.md
consensus/Cargo.toml
consensus/src/alerts/service.rs
consensus/src/backup/saver.rs
consensus/src/consensus.rs
consensus/src/creation/mod.rs
consensus/src/extender.rs
consensus/src/lib.rs
consensus/src/member.rs
consensus/src/network.rs
consensus/src/runway/mod.rs
consensus/src/runway/packer.rs
consensus/src/terminal.rs
consensus/src/testing/alerts.rs
consensus/src/testing/consensus.rs
consensus/src/testing/creation.rs
consensus/src/testing/dag.rs
consensus/src/testing/mod.rs
examples/blockchain/Cargo.toml
examples/blockchain/src/chain.rs
examples/blockchain/src/main.rs
examples/blockchain/src/network.rs
examples/ordering/src/main.rs
fuzz/Cargo.toml
fuzz/src/lib.rs
mock/Cargo.toml
types/Cargo.toml
types/src/lib.rs
types/src/terminator.rs

Move `Terminator` to `types` as it will be used also in `rmc`. So far `Terminator` resided in `consensus` making it impossible to be used by other components.

A0-3240: Move Terminator to types

---

Cargo.lock
README.md
consensus/Cargo.toml
consensus/src/runway/mod.rs
docs/src/aleph_bft_api.md
examples/ordering/src/dataio.rs
mock/Cargo.toml
mock/src/dataio.rs
types/Cargo.toml
types/src/dataio.rs

This pr is supposed to simplify the integration of Aleph Bft into Fedimint, a byzantine fault tolerant decentralised  chaumian ecash mint we call a Federation. Fedimint uses Aleph to order incoming transactions submitted by the clients. The inputs and outputs of the transaction are either chaumian ecash notes, on-chain bitcoin or smart contracts that enable integration with the bitcoin lightning network enabling instant settlement. After a transaction has been ordered by Aleph the system has to achieve consensus wether a transaction is valid by validating all inputs and outputs individually. 
An on-chain bitcoin input is the output of a bitcoin transaction that sends money to the Federation and is at least six blocks deep in the blockchain. Therefore we need to achieve consensus on the …

return the creator of a unit with the unit data when the unit is finalized

---

consensus/Cargo.toml
consensus/src/testing/consensus.rs
consensus/src/units/validator.rs

Control hashes of initial units have to refer to the empty parent set, so their combined hash is actually known _a priori_ and can be checked early. This also changes one test that used to assume a initial unit with a broken hash can be passed into consensus.
The only connection to A0-4006 is that the test in question failed after the refactor, since I didn't want to react to this incongruous situation internally.

A0-4006: Check initial unit control hashes early

---

Cargo.lock
README.md
consensus/Cargo.toml
consensus/src/backup/loader.rs
consensus/src/backup/saver.rs
consensus/src/member.rs
consensus/src/runway/mod.rs
examples/ordering/Cargo.toml
examples/ordering/src/main.rs
mock/Cargo.toml
mock/src/dataio.rs
rmc/Cargo.toml
rmc/src/handler.rs
rmc/src/scheduler.rs
rmc/src/service.rs

using `io::Write` or `io::Read` forces a sync implementation. 
we were using `block_on` to use async inside the implementation, but this blocking the executor and sometimes leads to deadlocks. 
this is backwards compatible by implementing new traits for any `io::Read` and `io::Write` impls.
see https://github.com/fedimint/fedimint/issues/4054 for more context.

Allow async implementation for BackupReader and BackupWriter

---

Cargo.lock
README.md
consensus/Cargo.toml
consensus/src/runway/mod.rs
examples/ordering/src/dataio.rs
mock/Cargo.toml
mock/src/dataio.rs
rmc/Cargo.toml
types/Cargo.toml
types/src/dataio.rs

Fedimint uses Aleph BFT to order a stream of transactions with unpredictable gaps between while ordering a transaction is latency critical. Hence we need to switch sessions before the exponential slowdown starts and can not wait for a fixed number of transactions to achieve consensus on when to trigger the next session switch. Currently nodes submit batches of transactions which may be empty and we trigger a session switch every fixed number of (possibly empty) batches. In a byzantine fault tolerant setting with 3f+1 nodes we can assume that we order at least f batches in every round, however, if all nodes are correct and online we will likely order 3f+1 batches per round, hence we switch the session about three times faster than necessary to prevent running into the exponential slowdown. …

return the round of a unit with the unit data when the unit is finalized

---

Cargo.lock
consensus/Cargo.toml
consensus/src/dag/reconstruction/dag.rs
consensus/src/dag/reconstruction/mod.rs
consensus/src/dag/reconstruction/parents.rs
consensus/src/extension/election.rs
consensus/src/extension/extender.rs
consensus/src/extension/mod.rs
consensus/src/extension/units.rs
consensus/src/runway/mod.rs
consensus/src/testing/dag.rs
consensus/src/units/mod.rs
consensus/src/units/testing.rs

A0-4215: Make extender synchronous

---

Cargo.lock
README.md
consensus/Cargo.toml
consensus/src/creation/mod.rs
consensus/src/dag/reconstruction/mod.rs
consensus/src/extension/mod.rs
consensus/src/lib.rs
consensus/src/member.rs
consensus/src/runway/mod.rs
consensus/src/testing/dag.rs
consensus/src/units/mod.rs
crypto/Cargo.toml
crypto/src/signature.rs
docs/src/aleph_bft_api.md
examples/blockchain/src/data.rs
examples/ordering/src/dataio.rs
mock/Cargo.toml
mock/src/dataio.rs
mock/src/network.rs
rmc/Cargo.toml
types/Cargo.toml
types/src/dataio.rs
types/src/lib.rs
types/src/network.rs

A separate method in member `run_session_for_units` that allows one to track finalization of batches of units.

A0-1672: units returned by run_session

---

Cargo.lock
consensus/Cargo.toml
consensus/src/dag/mod.rs
consensus/src/dag/reconstruction/dag.rs
consensus/src/dag/reconstruction/mod.rs
consensus/src/dag/reconstruction/parents.rs
consensus/src/dag/validation.rs
consensus/src/testing/dag.rs
consensus/src/units/store.rs
crypto/Cargo.toml
rust-toolchain.toml

This is necessary for the bump of `derive_more` to 1.0, which is also in this PR. The specific version is chosen for coherence with aleph-node.
All code changes are purely due to clippy becoming more demanding.

Bump rust toolchain to 1.77

---

Cargo.lock
consensus/src/extension/mod.rs
examples/ordering/Cargo.toml
examples/ordering/run.sh
examples/ordering/src/dataio.rs
examples/ordering/src/main.rs

* `example/ordering` binary now produces unique `DataProvider` input, so that the successful finish condition is that all nodes need to see at least one integer for union of all node's `DataProvider` items,
* reworked `run.sh`:
* support for passing unit creation delay (was the `defult_unit_creation_delay()`, which is 5000 ms, that is far greater than production values)
* added better crash simulation - now `run.sh` `kill`s node process, so it cannot anticipate crash

A0-4564: Modified example/ordering so that it sends unique elements from data provider

---

Cargo.lock
README.md
consensus/Cargo.toml
rmc/Cargo.toml

By the way, failures in the publishing workflow don't show up as failures in pipelines, only in some "annotations", very annoying. :<

A0-4341: Bump some versions that caused autopublishing to fail

---

Cargo.lock
consensus/Cargo.toml
consensus/src/dag/mod.rs
consensus/src/extension/election.rs
consensus/src/extension/extender.rs
consensus/src/units/mod.rs
consensus/src/units/testing.rs
consensus/src/units/validator.rs

Introduced 2 UTs, similar to existing ones, but with prepared DAG that contains non-direct parents. It turns out that current testing code almost support non-direct parents, as `ReconstructedUnit` control hash is created based on the parents injected by the test, except one method `random_unit_with_parents` that assumed each parent round is the same. 
Currently, those tests are disabled since they (expectedly) panic at 
```
units are added in order
thread 'extension::extender::test::given_minimal_dag_with_orphaned_node_when_producing_batches_have_correct_length' panicked at consensus/src/extension/election.rs:56:42:
```
This PR should not contain any changes to the production code.

A0-4563: Added unit test for censorship resistance in Extender

---

.github/workflows/cargo-audit.yml
Cargo.lock
README.md
consensus/Cargo.toml
consensus/src/dag/reconstruction/dag.rs
consensus/src/dag/reconstruction/mod.rs
consensus/src/dag/reconstruction/parents.rs
consensus/src/dissemination/responder.rs
consensus/src/extension/election.rs
consensus/src/extension/extender.rs
consensus/src/extension/units.rs
consensus/src/testing/dag.rs
consensus/src/units/mod.rs
consensus/src/units/testing.rs

This PR extends `UnitWithParents` trait so that it will be possible to distinguish direct and non-direct parents of a unit. Those changes are required for later changes in DAG reconstruction and validation. This change must be a no-op from the algorithm perspective. I am not going to uncomment UT added recently just yet,

A0-4563: Introduce notion of non-direct parents in Extender

---

Cargo.lock
consensus/Cargo.toml
consensus/src/testing/behind.rs
consensus/src/testing/byzantine.rs
consensus/src/testing/crash.rs
consensus/src/testing/crash_recovery.rs
consensus/src/testing/mod.rs
consensus/src/testing/unreliable.rs
mock/Cargo.toml
mock/src/dataio.rs
mock/src/lib.rs
mock/src/network.rs

Passes on the latest commit, hangs forever on the one just before.

A0-4566: Censorship resistance test

---

Cargo.lock
consensus/Cargo.toml
consensus/src/extension/extender.rs
consensus/src/units/testing.rs

Make sure ancient unit appears in some batch.

A0-4600: Fix ancient parent test

---

.github/workflows/cargo-audit.yml
.github/workflows/check-version-bumped-consensus.yml
.github/workflows/check-version-bumped-crypto.yml
.github/workflows/check-version-bumped-mock.yml
.github/workflows/check-version-bumped-rmc.yml
.github/workflows/check-version-bumped-types.yml
.github/workflows/ci.yml
.github/workflows/gh-pages.yml
.github/workflows/post-dod-checklist.yml
.github/workflows/publish-packages.yml
.github/workflows/push-foundation-repo.yml
.github/workflows/readme-cargo-toml-versions-aligned-consensus.yml

See https://github.com/actions/runner-images/issues/11101
Full `sed`. CI pass - it works!
https://github.com/Cardinal-Cryptography/AlephBFT/actions/runs/14107765268/job/39518251771?pr=550 fails in `main`, please ignore
Please delete options that are not relevant.
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

INFRA-205: Bump GitHub runners to 24.04

---

Cargo.lock
consensus/Cargo.toml
consensus/src/interface.rs
consensus/src/lib.rs
consensus/src/member.rs

Tiny PR, first of a couple. They should end with member & runway being completely replaced.

A0-4383: Move LocalIO into its own submodule

---

Cargo.lock
consensus/Cargo.toml
consensus/src/backup/loader.rs
consensus/src/collection/mod.rs
consensus/src/collection/service.rs
consensus/src/runway/mod.rs

This should _really_ be the penultimate PR.
Also ran `cargo update`, because dependabot was complaining about a vulnerability in `tokio` which we are not affected by.

A0-0000: Make backup loader less service-y

---

Cargo.lock
consensus/Cargo.toml
consensus/src/consensus/handler.rs
consensus/src/consensus/mod.rs
consensus/src/consensus/service.rs

Another refactor, this one needed for future implementations of alert backups.

A0-3477: Separate out the synchronous logic from consensus
